version: 2.0
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: ./deploy.sh
    filters:
      branches:
        only:
          - source
